### ISSUE TITLE
jade是不是不支持jdk8？

### ISSUE THREAD

**Issue by xugege** [paoding-code/paoding-rose#28]
paoding-rose依赖spring的版本为3.2，我看到网上一篇文章说spring3.2是不支持jdk8的？下面是文章链接地址
[http://blog.csdn.net/zl544434558/article/details/44758381](url)
[Rose-null@Spring-3.2.4.RELEASE]:I/O failure during jade scanning; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [E:\work\web\apache-tomcat-6.0.37\wtpwebapps\zen-admin\WEB-INF\classes\com\suoluo\zentravel\admin\dao\account\AccountBuyerDAO.class]; nested exception is java.lang.IllegalArgumentException
org.springframework.beans.factory.BeanDefinitionStoreException: I/O failure during jade scanning; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [E:\work\web\apache-tomcat-6.0.37\wtpwebapps\zen-admin\WEB-INF\classes\com\suoluo\zentravel\admin\dao\account\AccountBuyerDAO.class]; nested exception is java.lang.IllegalArgumentException
    at net.paoding.rose.jade.context.spring.JadeComponentProvider.findCandidateComponents(JadeComponentProvider.java:205)
    at net.paoding.rose.jade.context.spring.JadeBeanFactoryPostProcessor.findJadeDAODefinitions(JadeBeanFactoryPostProcessor.java:373)
    at net.paoding.rose.jade.context.spring.JadeBeanFactoryPostProcessor.doPostProcessBeanFactory(JadeBeanFactoryPostProcessor.java:311)
    at net.paoding.rose.jade.context.spring.JadeBeanFactoryPostProcessor.postProcessBeanFactory(JadeBeanFactoryPostProcessor.java:295)
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694)
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:684)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
    at net.paoding.rose.RoseFilter.prepareRootApplicationContext(RoseFilter.java:426)
    at net.paoding.rose.RoseFilter.initFilterBean(RoseFilter.java:268)
    at org.springframework.web.filter.GenericFilterBean.init(GenericFilterBean.java:194)
    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:295)
    at org.apache.catalina.core.ApplicationFilterConfig.setFilterDef(ApplicationFilterConfig.java:424)
    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:115)
    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4072)
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4726)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
    at org.apache.catalina.core.StandardHost.start(StandardHost.java:840)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
    at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
    at org.apache.catalina.core.StandardService.start(StandardService.java:525)
    at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
Caused by: org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [E:\work\web\apache-tomcat-6.0.37\wtpwebapps\zen-admin\WEB-INF\classes\com\suoluo\zentravel\admin\dao\account\AccountBuyerDAO.class]; nested exception is java.lang.IllegalArgumentException
    at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:56)
    at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80)
    at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102)
    at net.paoding.rose.jade.context.spring.JadeComponentProvider.findCandidateComponents(JadeComponentProvider.java:175)
    ... 27 more
Caused by: java.lang.IllegalArgumentException
    at org.springframework.asm.ClassReader.<init>(Unknown Source)
    at org.springframework.asm.ClassReader.<init>(Unknown Source)
    at org.springframework.asm.ClassReader.<init>(Unknown Source)
    at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:53)
    ... 30 more

**Comment by bsqql123** [comment]
@xugege 
提示信息里有这样一句话：
Java class file version that isn't supported yet: file [E:\work\web\apache-tomcat-6.0.37\

你用的是tomcat6 tomcat6 貌似不支持java 8吧，你升级一下tomcat到tomcat8或者8.5应该就支持了
