### ISSUE TITLE
rose 不支持jdk1.8

### ISSUE THREAD

**Issue by sugazaki** [paoding-code/paoding-rose#30]
Caused by: java.lang.IllegalStateException: Context namespace element 'annotation-config' and its parser class [org.springframework.context.annotation.AnnotationConfigBeanDefinitionParser] are only available on JDK 1.5 and higher
    at org.springframework.context.config.ContextNamespaceHandler$1.parse(ContextNamespaceHandler.java:65)
    at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:69)
    at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1297)
    at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1287)
    at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:135)
    at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:92)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:507)
    at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:398)

**Comment by met-pub** [comment]
你这报错是jdk版本低啊。。。

blog: http://bianbian.org

**Comment by sugazaki** [comment]
换成1.7就好了  

目测是rose引用了 
![image](https://cloud.githubusercontent.com/assets/1066802/15668119/3dafece8-274c-11e6-8800-fbbda4a7a527.png)

这个在jdk1.8中是跑不起来的

**Comment by met-pub** [comment]
这个不是rose引用的。这是spring低版本。你是不是有其他库依赖到了。
好像rose没有显式引用spring版本，你用什么版本就用什么版本。

我在1.8下完全能跑，我的spring是4.2.5

blog: http://bianbian.org

**Comment by bsqql123** [comment]
<dependency>
            <groupId>net.paoding</groupId>
            <artifactId>paoding-rose</artifactId>
            <version>2.0.u08</version>
        </dependency>


这个版本的rose应用的是Spring 3.x，可以直接使用jdk8

**Comment by hawkingfoo** [comment]
Rose和jade中排除掉Spring相关的包。再依赖spring4.1.4以上的版本就可以支持1.8了，亲测有效。
```
<dependency>
            <groupId>net.paoding</groupId>
            <artifactId>paoding-rose</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring-webmvc</artifactId>
                </exclusion>
            </exclusions>
```
如果有依赖jade，也要排除
```
<dependency>
            <groupId>net.paoding</groupId>
            <artifactId>paoding-rose-jade</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
